// components/vocab/styles.ts
// Shared StyleSheet for the Home/Learn screen and its practice/quiz modals.
// Moved out of app/(tabs)/index.tsx so the extracted modal components and the
// screen reference one identical style source instead of duplicating it.

import { Dimensions, StyleSheet } from "react-native";
import { Palette } from "@/constants/palette";

export const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Palette.bg },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  header: { alignItems: "center", paddingVertical: 20 },
  headerTitle: { fontSize: 26, fontWeight: "bold", color: Palette.accent },
  migrationBanner: { flexDirection: "row", alignItems: "center", marginTop: 8, backgroundColor: Palette.panel, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  migrationText: { color: Palette.accent, fontSize: 13 },
  card: { backgroundColor: Palette.card, borderRadius: 16, padding: 16, marginBottom: 16, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 6 },
  langRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  langBlock: { flex: 1 },
  langLabel: { color: Palette.textMuted, fontSize: 12, marginBottom: 4 },
  langPicker: { backgroundColor: Palette.inputBg, borderRadius: 8, paddingVertical: 10, paddingHorizontal: 12, borderWidth: 1, borderColor: Palette.primary },
  langPickerText: { color: Palette.brand, fontWeight: "600" },
  langArrow: { color: Palette.textDim, fontSize: 20, marginHorizontal: 12, alignSelf: "flex-end", marginBottom: 8 },
  actionRow: { flexDirection: "row", gap: 10 },
  btnPrimary: { flex: 1, backgroundColor: Palette.primary, paddingVertical: 14, borderRadius: 10, alignItems: "center" },
  btnQuiz: { flex: 1, backgroundColor: Palette.quiz, paddingVertical: 14, borderRadius: 10, alignItems: "center" },
  btnDisabled: { opacity: 0.5 },
  btnPrimaryText: { color: Palette.textPrimary, fontWeight: "bold", fontSize: 15 },
  btnCancel: { flex: 1, backgroundColor: "#333", paddingVertical: 14, borderRadius: 10, alignItems: "center" },
  btnCancelText: { color: Palette.textMuted, fontWeight: "bold", fontSize: 15 },
  statusText: { color: "#777", fontSize: 12, marginTop: 10, textAlign: "center" },
  wordRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginBottom: 12, gap: 12 },
  wordDisplay: { fontSize: 36, fontWeight: "bold", color: Palette.brand },
  ttsBtn: { padding: 6, borderRadius: 8 },
  ttsBtnText: { color: Palette.accent },
  overviewBox: { backgroundColor: Palette.panel, borderRadius: 10, padding: 12, marginBottom: 12 },
  overviewRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: 6 },
  rowWrap: { flexDirection: "row", flexWrap: "wrap", marginBottom: 6 },
  overviewKey: { color: Palette.info, fontWeight: "bold", fontSize: 13 },
  overviewValue: { color: "#E0E0E0", fontSize: 13, flex: 1, flexWrap: "wrap" },
  collocRow: { flexDirection: "row", flexWrap: "wrap" },
  collocToken: { color: Palette.hard, textDecorationLine: "underline", fontSize: 13 },
  exampleBox: { backgroundColor: Palette.inset, borderRadius: 10, padding: 12, marginBottom: 10 },
  diffRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  diffTag: { color: Palette.info, fontWeight: "bold", fontSize: 13 },
  sentenceBox: { backgroundColor: Palette.sentence, borderRadius: 8, padding: 12, marginBottom: 8 },
  sentenceText: { fontSize: 20, color: Palette.accent, fontWeight: "bold", lineHeight: 32, flexWrap: "wrap" },
  tokenText: { color: Palette.accent, textDecorationLine: "underline" },
  tokenizingRow: { flexDirection: "row", alignItems: "center", paddingVertical: 8 },
  tokenizingText: { color: Palette.textFaint, fontSize: 14, fontStyle: "italic" },
  translationPopup: { backgroundColor: "#1a1a1a", borderRadius: 10, padding: 12, borderWidth: 1, borderColor: Palette.success, marginTop: 8 },
  translationPopupHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 },
  translationPopupWord: { color: Palette.textFaint, fontSize: 12, fontStyle: "italic" },
  translationPopupText: { color: Palette.success, fontSize: 14, fontWeight: "bold" },
  translationPopupClose: { color: Palette.danger, marginTop: 8, textAlign: "right" },
  navRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginVertical: 10, gap: 20 },
  navBtn: { backgroundColor: Palette.primary, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 20 },
  navBtnText: { color: Palette.textPrimary, fontWeight: "bold" },
  counterText: { color: Palette.textPrimary, fontWeight: "bold", fontSize: 16 },
  controlRow: { flexDirection: "row", gap: 10, marginBottom: 10 },
  ctrlBtn: { flex: 1, backgroundColor: "#4a235a", borderRadius: 8, paddingVertical: 12, alignItems: "center", justifyContent: "center", minHeight: 44 },
  ctrlBtnMemory: { backgroundColor: "#7d3c1b" },
  ctrlBtnPractice: { backgroundColor: "#2d3f6f" },
  ctrlBtnText: { color: Palette.textPrimary, fontSize: 14, fontWeight: "700", letterSpacing: 0.2, textAlign: "center" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.7)", justifyContent: "flex-end" },
  pickerSheet: { backgroundColor: Palette.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20 },
  pickerTitle: { color: Palette.accent, fontSize: 18, fontWeight: "bold", marginBottom: 16, textAlign: "center" },
  pickerItem: { paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "#222" },
  pickerItemText: { color: Palette.textPrimary, fontSize: 16, textAlign: "center" },
  memCheckRoot: { flex: 1, backgroundColor: Palette.bg },
  memCheckHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, borderBottomWidth: 1, borderBottomColor: "#222", backgroundColor: Palette.card },
  memCheckTitle: { color: Palette.accent, fontSize: 20, fontWeight: "bold" },
  memCheckClose: { color: Palette.danger, fontSize: 22, fontWeight: "bold" },
  memCheckBody: { padding: 20 },
  memCheckProgress: { color: Palette.info, fontWeight: "bold", marginBottom: 10 },
  memCheckTtsRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  memCheckInstruction: { color: Palette.textMuted, fontSize: 14, flex: 1 },
  memCheckTranslation: { color: Palette.accent, fontSize: 18, fontStyle: "italic", marginBottom: 16, lineHeight: 26 },
  memCheckBtnRow: { flexDirection: "row", gap: 10, marginTop: 16 },
  memCheckDone: { flex: 1, justifyContent: "center", alignItems: "center", padding: 30 },
  memCheckDoneText: { color: Palette.success, fontSize: 18, textAlign: "center", marginBottom: 30, lineHeight: 28 },
  hintBtn: { flex: 1, backgroundColor: "#5d6d7e", borderRadius: 8, paddingVertical: 10, alignItems: "center" },
  hintBtnText: { color: Palette.textPrimary, fontWeight: "600" },
  typingRoot: { flex: 1, backgroundColor: Palette.bg },
  typingHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, borderBottomWidth: 1, borderBottomColor: "#222", backgroundColor: Palette.card },
  typingTitle: { color: Palette.accent, fontSize: 20, fontWeight: "bold" },
  typingBody: { padding: 20 },
  typingProgress: { color: Palette.info, fontWeight: "bold", marginBottom: 10 },
  typingPrompt: { color: Palette.textMuted, fontSize: 14, marginBottom: 10 },
  typingTargetBox: { backgroundColor: "#111", borderRadius: 10, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: "#333" },
  typingTargetText: { color: Palette.textPrimary, fontSize: 16, lineHeight: 22 },
  typingSuccessBox: { backgroundColor: "#223d1f", padding: 12, borderRadius: 10, marginTop: 12, marginBottom: 16 },
  typingSuccessText: { color: Palette.success, fontSize: 16, textAlign: "center" },
  quizSetupBox: { backgroundColor: Palette.card, borderRadius: 20, padding: 24, margin: 24, alignSelf: "center", width: width - 48 },
  quizSetupTitle: { color: Palette.accent, fontSize: 20, fontWeight: "bold", marginBottom: 12, textAlign: "center" },
  quizLangBadge: { backgroundColor: "#0d2a1a", borderRadius: 8, borderWidth: 1, borderColor: Palette.brand, paddingVertical: 6, paddingHorizontal: 12, alignSelf: "center", marginBottom: 14 },
  quizLangBadgeText: { color: Palette.brand, fontSize: 13, fontWeight: "600" },
  setupLabel: { color: Palette.textMuted, fontSize: 14, marginBottom: 8, marginTop: 10 },
  stepperRow: { flexDirection: "row", alignItems: "center", gap: 20, marginBottom: 4 },
  stepperBtn: { backgroundColor: Palette.primary, borderRadius: 8, paddingHorizontal: 18, paddingVertical: 8 },
  stepperText: { color: Palette.textPrimary, fontSize: 20, fontWeight: "bold" },
  stepperValue: { color: Palette.brand, fontSize: 22, fontWeight: "bold", minWidth: 40, textAlign: "center" },
  setupBtnRow: { flexDirection: "row", gap: 10, marginTop: 24 },
  quizRoot: { flex: 1, backgroundColor: Palette.bg },
  quizHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, backgroundColor: Palette.card, borderBottomWidth: 1, borderBottomColor: "#222" },
  quizTitle: { color: Palette.accent, fontSize: 18, fontWeight: "bold", flex: 1 },
  quizBody: { padding: 16, paddingBottom: 40 },
  quizQuestionCard: { backgroundColor: Palette.card, borderRadius: 12, padding: 16, marginBottom: 16 },
  quizQuestionText: { fontSize: 17, fontWeight: "bold", marginBottom: 14, lineHeight: 24 },
  quizOptionWrapper: { marginBottom: 6 },
  quizOption: { backgroundColor: Palette.inset, borderRadius: 8, paddingVertical: 12, paddingHorizontal: 16, marginBottom: 2, borderWidth: 1, borderColor: "#222" },
  quizOptionSelected: { borderColor: Palette.info, backgroundColor: "#112244" },
  quizOptionCorrect: { borderColor: Palette.success, backgroundColor: "#0d3320" },
  quizOptionWrong: { borderColor: Palette.danger, backgroundColor: "#2d0a0a" },
  quizOptionText: { color: Palette.textSecondary, fontSize: 15 },
  quizOptionMeta: { color: Palette.textMuted, fontSize: 12, marginTop: 4, marginLeft: 12 },
  quizExplanation: { color: Palette.warn, fontSize: 13, fontStyle: "italic", marginTop: 10, lineHeight: 20, backgroundColor: "#1a1a1a", padding: 10, borderRadius: 6 },
  quizSubmitBtn: { backgroundColor: "#27ae60", margin: 16, paddingVertical: 16, borderRadius: 12, alignItems: "center" },
  quizScoreBar: { backgroundColor: Palette.primary, margin: 16, paddingVertical: 16, borderRadius: 12, alignItems: "center" },
  quizScoreText: { color: Palette.textPrimary, fontSize: 18, fontWeight: "bold" },
  explainBtn: { backgroundColor: Palette.border, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 14, alignSelf: "flex-start", marginTop: 2, borderWidth: 1, borderColor: "#2980b9" },
  explainBtnText: { color: Palette.info, fontWeight: "600", fontSize: 13 },
  explainLoading: { flexDirection: "row", alignItems: "center", marginTop: 6 },
  explainLoadingText: { color: Palette.warn, fontSize: 13, fontStyle: "italic" },
  quizExplanationBox: { backgroundColor: "#1a1a1a", borderRadius: 8, padding: 10, marginTop: 4, borderLeftWidth: 3, borderLeftColor: Palette.warn },
  wordInputRow: { flexDirection: "row", alignItems: "center", marginBottom: 14, gap: 8 },
  wordInput: { backgroundColor: Palette.inputBg, color: Palette.textPrimary, borderRadius: 10, padding: 14, fontSize: 18, borderWidth: 1, borderColor: Palette.primary },
  lessonNavArrow: { backgroundColor: Palette.primary, borderRadius: 10, width: 42, height: 74, alignItems: "center", justifyContent: "center" },
  lessonNavArrowText: { color: Palette.brand, fontSize: 18, fontWeight: "bold" },
  lessonNavHint: { color: Palette.info, fontSize: 11, marginTop: 4, marginLeft: 4, fontStyle: "italic" },

  flipIconBtn: {
    padding: 4,
    borderRadius: 6,
    backgroundColor: Palette.border,
  },
  flipIconText: {
    fontSize: 16,
  },
  flipCardWrapper: {
    minHeight: 80,
    position: "relative",
  },
  flipCardFace: {
    backfaceVisibility: "hidden",
    width: "100%",
  },
  flipCardFront: {
    // default position (in flow)
  },
  flipCardBack: {
    padding: 4,
  },
});

export const mcStyles = StyleSheet.create({
  tabs:          { flexDirection: "row", gap: 10, marginTop: 16, marginBottom: 4 },
  tab:           { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: "center", backgroundColor: Palette.panel, borderWidth: 1, borderColor: Palette.border },
  tabActive:     { backgroundColor: Palette.primary, borderColor: Palette.brand },
  tabText:       { color: Palette.textFaint, fontWeight: "600", fontSize: 14 },
  tabTextActive: { color: Palette.brand },
});
